---
# dev secrets can be constant
apiVersion: v1
kind: Secret
metadata:
  name: linkiguess-secrets
type: Opaque
stringData:
  GRAFANA_INITIAL_PASSWORD: "admin"
  LINK_DB_PASSWORD: "75ed0b1fc6cad0826cac98d5458dcc81abd22cb950d6cbaf8480cf0f9673f3d3"
  ANALYTIC_NATS_PASSWORD: "6101b373a4fca4a11eeba47e5878ceeb595a679afac7c90e9118f2cf61478bb7"
